package: libdynd_build_test
platform:
    - linux-64
    - osx-64
    - win-64
script:
    - conda -c r build conda.recipe
build_targets:
    files: conda
    channels: main
iotimeout: 300

# before_script:
#     - sudo yum -y install git dos2unix gcc gcc-c++
