package: libdynd_build_test
platform:
    - linux-64
    - osx-64
    - win-64
script:
    - conda config --set binstar_upload yes
    - conda build conda.recipe -c stuarteberg
build_targets:
    files: conda
    channels: main
iotimeout: 300

# before_script:
#     - sudo yum -y install git dos2unix gcc gcc-c++
