language: cpp

compiler:
  - gcc
  - clang

env:
  - DYND_FFTW=OFF VALGRIND=ON
  - DYND_FFTW=ON
  - DYND_FFTW=ON ASAN=ON

matrix:
  exclude:
    - compiler: gcc
      env: DYND_FFTW=ON ASAN=ON


before_script:
  - sudo apt-get update
  - if [ "$VALGRIND" == "ON" ]; then sudo apt-get -qq install valgrind; fi
  - if [ "$DYND_FFTW" == "ON" ]; then sudo apt-get -qq install libfftw3-dev; fi
  - if [ "$ASAN" == "ON" ]; then export CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer'; fi
  - mkdir build
  - cd build
  - cmake -DDYND_FFTW=${DYND_FFTW} ..

script:
  - make
  - ./tests/test_libdynd
  - if [ "$VALGRIND" == "ON" ]; then valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --error-exitcode=123 ./tests/test_libdynd; fi

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"
