language: cpp

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - cmake
    - valgrind
    - libfftw3-dev

compiler:
  - gcc
  - clang

env:
  - VALGRIND=ON DYND_CUDA=OFF DYND_FFTW=OFF
#  - DYND_CUDA=ON DYND_FFTW=OFF
  - DYND_CUDA=OFF DYND_FFTW=ON
  - ASAN=ON DYND_CUDA=OFF DYND_FFTW=ON
#  - PYTHON=ON DYND_CUDA=OFF DYND_FFTW=ON DYND_BUILD_TESTS=OFF DYND_BUILD_BENCHMARKS=OFF
#  - MSAN=ON DYND_CUDA=OFF DYND_FFTW=ON

matrix:
  exclude:
    - compiler: gcc
      env: ASAN=ON DYND_CUDA=OFF DYND_FFTW=ON
    - compiler: gcc
      env: MSAN=ON DYND_CUDA=OFF DYND_FFTW=ON
#    - compiler: gcc
#      env: PYTHON=ON DYND_CUDA=OFF DYND_FFTW=ON DYND_BUILD_TESTS=OFF DYND_BUILD_BENCHMARKS=OFF
    - compiler: clang
      env: DYND_CUDA=ON DYND_FFTW=OFF

before_script:
  - if [ "$CC" = "gcc" ]; export CC="gcc-4.7"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7"; fi
#  - if [ "$DYND_CUDA" == "ON" ]; then wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb;
#    sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb; sudo apt-get update; sudo apt-get -y install cuda; fi
#  - if [ "$PYTHON" == "ON" ]; then travis_retry pip install numpy cython; fi
  - if [ "$ASAN" == "ON" ]; then export CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer'; fi
  - if [ "$MSAN" == "ON" ]; then export CXXFLAGS='-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer'; fi
  - if [ "$DYND_BUILD_TESTS" == "" ]; then export DYND_BUILD_TESTS=ON; fi
  - if [ "$DYND_BUILD_BENCHMARKS" == "" ]; then export DYND_BUILD_BENCHMARKS=ON; fi
  - mkdir build
  - pushd build
  - cmake $(if [ $DYND_CUDA = ON ]; then echo -DCMAKE_BUILD_TYPE=RelWithDebInfo; fi) -DDYND_CUDA=${DYND_CUDA} -DDYND_FFTW=${DYND_FFTW} -DDYND_BUILD_TESTS=${DYND_BUILD_TESTS} -DDYND_BUILD_BENCHMARKS=${DYND_BUILD_BENCHMARKS} ..

script:
  - make || exit 1
  - if [ "$DYND_CUDA" == "ON" ]; then exit; fi
  - if [ "$DYND_BUILD_TESTS" == "ON" ]; then ./tests/test_libdynd; fi
  - if [ "$VALGRIND" == "ON" ]; then valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --error-exitcode=123 ./tests/test_libdynd; fi
#  - if [ "$PYTHON" == "ON" ]; then make install; sudo ldconfig; popd; fi
#  - if [ "$PYTHON" == "ON" ]; then git clone https://github.com/libdynd/dynd-python.git; fi
#  - if [ "$PYTHON" == "ON" ]; then pushd dynd-python && python setup.py install; popd; fi
#  - if [ "$PYTHON" == "ON" ]; then python -c 'import dynd;dynd.test(exit=True)'; fi

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"
