sudo: false

matrix:
  include:
    - language: python
      env: DYND_FFTW=OFF VERBOSE=1
      compiler: clang
      python: 2.7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - g++-4.7
          - cmake
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/dynd-python/build
      before_install:
        - export CC=clang
        - export CXX=clang++
        - travis_retry pip install --install-option="--no-cython-compile" Cython==0.22
      before_script:
        - cd ..
        - travis_retry git clone --depth=1 https://github.com/libdynd/dynd-python.git
        - mkdir dynd-python/libraries
        - mv libdynd dynd-python/libraries/libdynd
        - cd dynd-python
      script:
        - python -c "import numpy; print numpy.__version__"
        - python setup.py install
        - cd ..
        - python -c "import dynd; dynd.test(exit=True)"
    - language: python
      env: DYND_FFTW=OFF VERBOSE=1
      compiler: clang
      python: 2.7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - g++-4.7
          - cmake
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/dynd-python/build
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b
        - export PATH=$HOME/miniconda/bin:$PATH
        - if [ $TRAVIS_BRANCH == "master" ]; then conda config --set binstar_upload yes; fi
        - conda install --yes conda-build anaconda-client
        - conda install --yes cython numpy setuptools
      before_script:
        - export CC="gcc-4.7"
        - export CXX="g++-4.7"
      script:
        - conda build conda.recipe
      after_success:
        - if [ $TRAVIS_BRANCH == "master" ]; then echo 'Success'; fi
    - compiler: gcc
      env: VALGRIND=ON DYND_FFTW=OFF
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - gcc-4.7
          - g++-4.7
          - cmake
          - valgrind
      before_install:
        - export CC="gcc-4.7"
        - export CXX="g++-4.7"
    - compiler: gcc
      env: DYND_FFTW=ON
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - gcc-4.7
          - g++-4.7
          - cmake
          - libfftw3-dev
      before_install:
        - export CC="gcc-4.7"
        - export CXX="g++-4.7"
    - compiler: clang
      env: VALGRIND=ON DYND_FFTW=OFF
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - g++-4.7
          - cmake
          - valgrind
      script:
        - make || exit 1
        - ./tests/test_libdynd
        - valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --error-exitcode=123 ./tests/test_libdynd
    - compiler: clang
      env: DYND_FFTW=ON CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer'
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - g++-4.7
          - cmake
          - libfftw3-dev
    - compiler: clang
      env: DYND_FFTW=ON
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          packages:
          - g++-4.7
          - cmake
          - libfftw3-dev

language: cpp

cache:
  directories:
    - $HOME/libdynd/build

before_script:
  - mkdir build
  - pushd build
  - cmake -DDYND_FFTW=${DYND_FFTW} -DDYND_BUILD_BENCHMARKS=ON ..

script:
  - make || exit 1
  - ./tests/test_libdynd

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"
