# branches to build
branches:
  only:
    - master
clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:
    - PYTHON_ARCH: "x86_64"
    - PYTHON_ARCH: "x86"

platform:
  - Win32
  - x64

configuration: Release

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install conda-build
  - pip install git+git://github.com/conda/conda-build.git
  - conda-build conda.recipe

