package:
  name: libdynd
  version: 0.0

source:
  git_url: https://github.com/ContinuumIO/libdynd.git
  git_tag: master

requirements:
  build:
    - cmake           [linux]

about:
  home: https://github.com/ContinuumIO/libdynd
  license: BSD

