package:
  name: libdynd
  version: 0.7.0

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - cmake [unix]
    - gcc >=4.8 [linux]
  run:
    - libgcc >=4.8 [linux]

test:
  commands:
    - test_libdynd

about:
  home: https://github.com/libdynd/libdynd
  license: BSD

