package:
  name: libdynd
  version: 0.7.0

build:
  number: 1

requirements:
  build:
    - cmake [unix]
    - gcc >=4.8
  run:
    - libgcc >=4.8

test:
  commands:
    - test_libdynd

about:
  home: https://github.com/libdynd/libdynd
  license: BSD

