package:
  name: libdynd
  version: 0.7.0

build:
  number: {{environ.get('TRAVIS_BUILD_NUMBER', 0)}}
  script_env:
    - CC [linux]
    - CXX [linux]

test:
  commands:
    - test_libdynd

about:
  home: https://github.com/libdynd/libdynd
  license: BSD
